# Generated by Django 4.2.30 on 2026-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StellarGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=255)),
                ('star_classification', models.CharField(help_text='Spectral class (O, B, A, F, G, K, M, etc.)', max_length=50)),
                ('luminosity_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature', models.IntegerField(default=0, verbose_name='Temperature (K)')),
                ('mass', models.TextField(blank=True, null=True)),
                ('elemental_composition', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('birth', models.TextField(blank=True, null=True)),
                ('life', models.TextField(blank=True, null=True)),
                ('death', models.TextField(blank=True, null=True)),
                ('reincarnation', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default='')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
